# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.upd_time = QtWidgets.QLabel(self.groupBox)
        self.upd_time.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.upd_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.upd_time.setObjectName("upd_time")
        self.horizontalLayout_3.addWidget(self.upd_time)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.max_age = QtWidgets.QSpinBox(self.groupBox_2)
        self.max_age.setMinimum(2)
        self.max_age.setMaximum(100)
        self.max_age.setProperty("value", 3)
        self.max_age.setObjectName("max_age")
        self.verticalLayout.addWidget(self.max_age)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.end_breeding_age = QtWidgets.QSpinBox(self.groupBox_2)
        self.end_breeding_age.setMinimum(1)
        self.end_breeding_age.setMaximum(100)
        self.end_breeding_age.setObjectName("end_breeding_age")
        self.verticalLayout.addWidget(self.end_breeding_age)
        self.gridLayout.addWidget(self.groupBox_2, 8, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.play = QtWidgets.QPushButton(self.groupBox)
        self.play.setEnabled(True)
        self.play.setText("")
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.play.setIcon(icon)
        self.play.setCheckable(True)
        self.play.setObjectName("play")
        self.horizontalLayout_2.addWidget(self.play)
        self.pause = QtWidgets.QPushButton(self.groupBox)
        self.pause.setEnabled(True)
        self.pause.setText("")
        icon = QtGui.QIcon.fromTheme("media-playback-pause")
        self.pause.setIcon(icon)
        self.pause.setCheckable(True)
        self.pause.setObjectName("pause")
        self.horizontalLayout_2.addWidget(self.pause)
        self.clear = QtWidgets.QPushButton(self.groupBox)
        self.clear.setEnabled(True)
        self.clear.setText("")
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.clear.setIcon(icon)
        self.clear.setCheckable(False)
        self.clear.setObjectName("clear")
        self.horizontalLayout_2.addWidget(self.clear)
        self.new_btn = QtWidgets.QPushButton(self.groupBox)
        self.new_btn.setText("")
        icon = QtGui.QIcon.fromTheme("document-new")
        self.new_btn.setIcon(icon)
        self.new_btn.setObjectName("new_btn")
        self.horizontalLayout_2.addWidget(self.new_btn)
        self.spawn_btn = QtWidgets.QPushButton(self.groupBox)
        self.spawn_btn.setEnabled(True)
        self.spawn_btn.setObjectName("spawn_btn")
        self.horizontalLayout_2.addWidget(self.spawn_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 12, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.enable_aging_btn = QtWidgets.QCheckBox(self.groupBox)
        self.enable_aging_btn.setObjectName("enable_aging_btn")
        self.gridLayout.addWidget(self.enable_aging_btn, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.color_scheme = QtWidgets.QComboBox(self.groupBox)
        self.color_scheme.setObjectName("color_scheme")
        self.color_scheme.addItem("")
        self.color_scheme.addItem("")
        self.gridLayout.addWidget(self.color_scheme, 6, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 1)
        self.cell_size = QtWidgets.QSpinBox(self.groupBox)
        self.cell_size.setMinimum(5)
        self.cell_size.setMaximum(40)
        self.cell_size.setProperty("value", 10)
        self.cell_size.setObjectName("cell_size")
        self.gridLayout.addWidget(self.cell_size, 4, 0, 1, 2)
        self.upd_time_slider = QtWidgets.QSlider(self.groupBox)
        self.upd_time_slider.setMaximum(1000)
        self.upd_time_slider.setProperty("value", 60)
        self.upd_time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.upd_time_slider.setInvertedAppearance(False)
        self.upd_time_slider.setInvertedControls(False)
        self.upd_time_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.upd_time_slider.setTickInterval(100)
        self.upd_time_slider.setObjectName("upd_time_slider")
        self.gridLayout.addWidget(self.upd_time_slider, 2, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.generation_value = QtWidgets.QLabel(self.groupBox_3)
        self.generation_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.generation_value.setObjectName("generation_value")
        self.gridLayout_2.addWidget(self.generation_value, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 10, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHow_to_use = QtWidgets.QAction(MainWindow)
        self.actionHow_to_use.setObjectName("actionHow_to_use")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Game of Life"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "Update interval"))
        self.upd_time.setText(_translate("MainWindow", "60ms"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Aging settings"))
        self.label_3.setText(_translate("MainWindow", "Maximum age"))
        self.label_4.setText(_translate("MainWindow", "End of breeding age"))
        self.spawn_btn.setText(_translate("MainWindow", "Spawn"))
        self.label_2.setText(_translate("MainWindow", "Cell size"))
        self.enable_aging_btn.setText(_translate("MainWindow", "Enable aging"))
        self.label_5.setText(_translate("MainWindow", "Color scheme"))
        self.color_scheme.setItemText(0, _translate("MainWindow", "Green"))
        self.color_scheme.setItemText(1, _translate("MainWindow", "White/Black"))
        self.cell_size.setSuffix(_translate("MainWindow", "px"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Stats"))
        self.generation_value.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Generation"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionHow_to_use.setText(_translate("MainWindow", "How to use"))
        self.actionHow_to_use.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
